<Project Sdk="Nice3point.Revit.Sdk/6.2.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Kapibara.RevitToolKit.Core\Kapibara.RevitToolKit.Core.csproj" />
      <ProjectReference Include="..\SheetManager\SheetManager.csproj" />
    </ItemGroup>

</Project>
